"""add otp fields

Revision ID: 3fe203ca85f2
Revises: 4dcd0608e967
Create Date: 2026-07-04 23:50:46.244845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe203ca85f2'
down_revision: Union[str, None] = '4dcd0608e967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('otp_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_sent_at')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
