"""add fraud verification and feedback rating fields

Revision ID: 8ee21812cd3a
Revises: 3fe203ca85f2
Create Date: 2026-07-05 16:24:44.470281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee21812cd3a'
down_revision: Union[str, None] = '3fe203ca85f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('volunteer_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'volunteer_accepted')
    # ### end Alembic commands ###
